export interface VehicleOfInterest {
  year: string
  make: string
  model: string
  price: string
  mileage: string
  vin: string
  cashDown: string
}
export interface CreditApplicant {
  employedPrimary: string
  firstName: string
  middleName: string
  lastName: string
  phone: string
  phoneType: string
  email: string
  dateOfBirth: string
  ssn: string
  addressLine1: string
  city: string
  state: string
  zipCode: string
  addressYears: string
  addressMonths: string
  rentMortgagePaymentAmount: string
  licenseNumber?: string
  licenseState?: string
  employerName: string
  employmentStatusCode: string
  employerPhone: string
  employmentTitle: string
  timeOnJobYears: string
  timeOnJobMonths: string
  incomeAmount: string
  previousEmployerName: string
  prevEmployerPhone: string
  prevEmploymentTitle: string
  prevTimeOnJobYears: string
  prevTimeOnJobMonths: string
  prevIncomeAmount: string
  prevAddressLine1: string
  prevCity: string
  prevState: string
  prevZipCode: string
  prevAddressYears: string
  prevAddressMonths: string
  prevRentMortgagePaymentAmount: string
  otherIncomeSourceCode: string
  otherIncomeAmount: string
  otherIncomeSourceDescription: string
}
